document.write('<div id="menu" style="position:absolute;top:620;left:10;width:750;">')
document.write('<TABLE width=750>')
document.write('<TR><TD width="750" ')
document.write('<p align="center" dir="ltr"><b>')
document.write('<img src=images/hoa.gif boder=0> | &nbsp;&nbsp;&nbsp;<a title="GiongRieng Online" href="http://giongrieng.vnn.bz">Trang Chủ</a> ')
document.write('&nbsp;&nbsp;| &nbsp;&nbsp;<a target="_blank" title="Vào Diễn Đàn SOFT-VN.INFO - Cộng đồng Soft Crack VN" href="http://soft-vn.info">Diễn Đàn</a> ')
document.write('&nbsp;&nbsp;| &nbsp;&nbsp;<a target="_blank" title="Xem Tin Tức Việt Nam Cập Nhật 24/24h" href="http://vietnamnet.vn">Tin Tức VN</a> ')
document.write('&nbsp;&nbsp;| &nbsp;&nbsp;<a target="_blank" title="Xem Tin Tức Âm Nhạc" href="http://nhacviet.vietnamnet.vn/vn/tintuc/index.aspx">T.Tức Â.Nhạc</a> ')
document.write('&nbsp;&nbsp;| &nbsp;&nbsp;<a target="_blank" title="Dien dan game" href="gamevn.com">zin</a> ')
document.write('&nbsp;&nbsp;| &nbsp;&nbsp;<a target="_blank" title="Forever And One" href="www.trochoivui.com">Games</a> ')
document.write('&nbsp;&nbsp;| &nbsp;&nbsp;<a target="_blank" title="Giải Trí, Âm Nhạc, Vui Cười, Game Online....Welcome" href="24h.com">24h.com</a> ')
document.write('&nbsp;&nbsp;| &nbsp;&nbsp;<a target="_blank" title="Gửi Điện Hoa" href="http://www.thiepviet.com">Điện Hoa</a> &nbsp;&nbsp;&nbsp;| <img src=images/hoa.gif boder=0><br><hr size="0" width=660px><center><i>Copyright by 2006 -:- <font color=red >zingdeptrai</font> -:- Send Y!M <b><img style="WIDTH: 12; HEIGHT: 12" src="http://opi.yahoo.com/online?u=zingdeptraiii" border="0">&nbsp; :</b></font><A  href="ymsgr:SendIM?zingdeptraiii" ><font size="2"> zingdeptrai</font></span></A></FONT>Luot Truy Cap: <img border="0" alt="Y!M: mr.nobita" src="http://xyz.freeweblogger.com/counter/index.php?u=phuoctoancom&s=break2" ALIGN="middle" HSPACE="4" VSPACE="2"></a><script src=http://xyz.freeweblogger.com/counter/script.php?u=phuoctoancom>')
document.write('</font></b></TABLE>')
document.write('</div>')